src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Intership;
use App\Entity\IntershipPlace;
use App\Entity\ApplicationField;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * 
     * @ORM\Column(type="string")
     */
    private $lastname;
    /**
     * @ORM\Column(type="string")
     */
    private $firstname;
    /**
     * @ORM\Column(type="string")
     */
    private $email;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string")
    */
     private $type;
    /**
     * @ORM\ManyToMany(targetEntity=IntershipPlace::class)
     */
    private $intership;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    /**
     * @ORM\ManyToOne(targetEntity=ApplicationField::class, inversedBy="users")
     */
    private $applicationField;

    /**
     * @ORM\ManyToMany(targetEntity=Intership::class, mappedBy="referents")
     */
    private $interships;

    /**
     * @ORM\OneToMany(targetEntity=Evaluation::class, mappedBy="user", orphanRemoval=true)
     */
    private $evaluations;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $hasSharedFile;


    public function __construct()
    {
        $this->intership = new ArrayCollection();
        $this->interships = new ArrayCollection();
        $this->evaluations = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastname;
    }

    public function setLastName(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstname;
    }

    public function setFirstName(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->email;
    }

    public function setMail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|IntershipPlace[]
     */
    public function getIntership(): Collection
    {
        return $this->intership;
    }

    public function addIntership(IntershipPlace $intership): self
    {
        if (!$this->intership->contains($intership)) {
            $this->intership[] = $intership;
        }

        return $this;
    }

    public function removeIntership(IntershipPlace $intership): self
    {
        $this->intership->removeElement($intership);

        return $this;
    }

    public function getApplicationField(): ?ApplicationField
    {
        return $this->applicationField;
    }

    public function setApplicationField(?ApplicationField $applicationField): self
    {
        $this->applicationField = $applicationField;

        return $this;
    }

    /**
     * @return Collection|Intership[]
     */
    public function getInterships(): Collection
    {
        return $this->interships;
    }

   

     /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        switch($this->getType()){
            case 'Etudiant':
                $roles[]='ROLE_STUDENT';
                break;
            case 'Référent':
                $roles[]='ROLE_REFERENT';
                break;
            case 'Enseignant':
                $roles[]='ROLE_TEACHER';
                break;
            case 'Administrateur':
                $roles[]='ROLE_ADMIN';
                break;
        }
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Evaluation[]
     */
    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    public function addEvaluation(Evaluation $evaluation): self
    {
        if (!$this->evaluations->contains($evaluation)) {
            $this->evaluations[] = $evaluation;
            $evaluation->setUser($this);
        }

        return $this;
    }

    public function removeEvaluation(Evaluation $evaluation): self
    {
        if ($this->evaluations->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getUser() === $this) {
                $evaluation->setUser(null);
            }
        }

        return $this;
    }

    public function getHasSharedFile(): ?bool
    {
        return $this->hasSharedFile;
    }

    public function setHasSharedFile(?bool $hasSharedFile): self
    {
        $this->hasSharedFile = $hasSharedFile;

        return $this;
    }
    
}

src/Controller/EvaluationController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;
use App\Entity\Skill;
use App\Entity\Cotation;
use App\Entity\Intership;
use App\Entity\Evaluation;
use Knp\Snappy\Pdf as Snappy;
use App\Form\FileSendFormType;
use App\Entity\GlobalEvaluation;
use App\Entity\SubSkillCotation;
use App\Form\SubmitTypeFormType;
use App\Entity\GlobalEvaluationSkill;
use Office365\SharePoint\ClientContext;
use Doctrine\ORM\EntityManagerInterface;
use Office365\Runtime\Auth\UserCredentials;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class EvaluationController extends AbstractController
{

    private $em,$mailer,$security,$kernel;
    public function __construct(EntityManagerInterface $entityManager,MailerInterface $mailer, Security $security, KernelInterface $kernel)
    {
        $this->em = $entityManager;
        $this->mailer=$mailer;
        $this->security = $security;
        $this->kernel = $kernel;
    }

    


    /**
     * @Route("/evaluation/intership",name="viewEvaluationIntership")
     * @IsGranted("ROLE_TEACHER")
     */
    public function getListIntership(): Response
    {
        $listIntership = $this->em->getRepository(Intership::class)->findAll();
        return $this->render('evaluation/listIntership.html.twig', [
            'interships' => $listIntership
        ]);
    }
    /**
     * @Route("/evaluation/intership/{id}", name="viewEvaluation")
     * @IsGranted("ROLE_TEACHER")
     */
    public function listStudent(Intership $intership): Response
    {
        $students = [];
        $evaluations = $this->em->getRepository(Evaluation::class)->findAll();

        foreach ($intership->getApplicationField()->getUsers() as $student) {
            
                array_push($students, $student);
            
        }
        return $this->render('evaluation/index.html.twig', [

            'students' => $students,
            'intership' => $intership
        ]);
    }
 

    /**
     * @Route("/evaluation/{id}/evaluer/{idIntership}",name="listEvaluation")
     * @ParamConverter("intership", options={"id" = "idIntership"})
     * @IsGranted("ROLE_TEACHER")
     */
    public function listSkills(User $student, Intership $intership, Request $request): Response
    {
       
        $evaluations = $this->em->getRepository(Evaluation::class)->findBy(['typeEvaluation'=>'Evaluation','user'=>$this->security->getUser()->getId(),'state'=>'Modification']);
        $evaluationArchive = new Evaluation();
        foreach($evaluations as $evaluation){
            if($evaluation->getCotation()[0]->getUser() == $student && $evaluation->getCotation()[0]->getIntership() == $intership ){
                
                return $this->render('evaluation/createEvaluation.html.twig', [
                    'evaluation'=>$evaluation
                ]);
        }
        }
        $cotations = [];
            $listSkill = $intership->getSkills();
            
            foreach ($listSkill as $skill) {
                if (sizeof($skill->getSubSkills()) == 0) {
                    array_splice($listSkill, array_search($skill, $listSkill), 1);
                }
            }
            $evaluationArchive->setState("Modification");
            $evaluationArchive->setTypeEvaluation("Evaluation");
            $evaluationArchive->setUser($this->security->getUser());
            foreach ($listSkill as $skill) {
                $cotation = new Cotation();
                $cotation->setUser($student);
                $cotation->setSkill($skill);
                $cotation->setIntership($intership);
                foreach ($skill->getSubSkills() as $subskill) {
                    $subCotation = new SubSkillCotation();
                    $subCotation->setSubSkill($subskill);
                    $subCotation->setCotation(0);
                    $cotation->addSubskillcotation($subCotation);
                }
                array_push($cotations,$cotation);
                $this->em->persist($cotation);
                $this->em->flush();
                
            }
            foreach ($cotations as $cotation) {
               $evaluationArchive->addCotation($cotation);
            }
    
            $this->em->persist($evaluationArchive);
            $this->em->flush();
        
        return $this->redirectToRoute('listEvaluation',['id'=>$student->getId(),'idIntership'=>$intership->getId()]);
    }

    /**
     * @Route("/evaluation/cloture/{id}",name="endEvaluation")
     * @IsGranted("ROLE_TEACHER")
     */
    public function endEvaluation(Evaluation $evaluation, Request $request, Snappy $snappy)
    {
        //Création d'un formulaire
        $form = $this->createForm(SubmitTypeFormType::class);
        $form->handleRequest($request);

        
        /**
         *  Vérifier si il existe des cotations
         *  Si il n'existe pas de cotations, l'utilisateur sera renvoyé sur une autre page
        */
        if ($evaluation->getCotation() == null) {
            $this->addFlash('danger', "Aucune évaluation n'est créée");
            return $this->redirectToRoute('viewEvaluation', ['id' => $evaluation->getCotation()[0]->getIntership()->getId()]);
        }

        /**
         * Nous allons vérifier si toutes les cotations sont correctes
         * CAD vérifier si toutes les sous-compétences ont une côte
         * Les côtes définies sont NA--,NA-, A+ et A++
         */
        $nbCotationError = 0;
        foreach ($evaluation->getCotation() as $cotation) {
            foreach ($cotation->getsubSkillcotation() as $subcotation) {
                if ($subcotation->getCotation() == 0) {
                    $nbCotationError++;
                }
            }
        }

        /**
         * Si il y a des erreurs, l'utilisateur sera redirigé vers la page d'évaluation de l'étudiant
         */
        if ($nbCotationError != 0) {
            $this->addFlash('danger',  $nbCotationError . " sous-compétence(s) n'est/ne sont pas évaluée(s)");
            return $this->redirectToRoute('listEvaluation', ['id' => $evaluation->getCotation()[0]->getUser()->getId(), 'idIntership' => $evaluation->getCotation()[0]->getIntership()->getId()]);
        }

        /**
         * Recherche les évaluations dans la Base de données
         */
            foreach ($evaluation->getCotation() as $cotationEvaluated) {
                    if($evaluation->getPosition() != ''){
                        if($evaluation->getCotation()[0]->getIntership()->getFirstDay()<$evaluation->getDateCreation() && $evaluation->getCotation()[0]->getIntership()->getLastDay()>$evaluation->getDateCreation()){
                            /**
                             * Lorsque le formulaire est validé
                             */
                            if ($form->isSubmitted()) {
                                $html = $this->renderView('evaluation/evaluationStudent.html.twig', [
                                    'evaluation' => $evaluation
                                ]);
                                $snappy->setOption('header-left',"Encodé par Mr/Mme ".$this->security->getUser()->getFirstName().' '.$this->security->getUser()->getLastName());
                                $snappy->setOption('header-line', true);
                                $snappy->setOption('footer-line', true);
                                $snappy->setOption('footer-center','Page [page] of [topage]');
                                $evaluation->setState("Fini");
                                $listGlobalEvaluation = $this->em->getRepository(GlobalEvaluation::class)->findAll();
                                /**
                                 * Nous allons placer l'évaluation dans une liste d'évaluation qu'on nommera Evaluation-Globale
                                 */
                                if($listGlobalEvaluation == null){
                                    $globalEvaluation = new GlobalEvaluation();
                                    $globalEvaluation->setCreatedDate(new DateTime());
                                    $globalEvaluation->setState('Modification');
                                    $this->em->persist($globalEvaluation);
                                    $globalEvaluation->addEvaluation($evaluation);
                                }
                                else{
                                    if(sizeof($listGlobalEvaluation)==1){
                                        if($listGlobalEvaluation[0]->getEvaluations()[0]->getCotation()[0]->getIntership()->getAnsco() == $evaluation->getCotation()[0]->getIntership()->getAnsco()
                                            && $listGlobalEvaluation[0]->getEvaluations()[0]->getCotation()[0]->getUser() == $evaluation->getCotation()[0]->getUser()
                                        ){
                                            $listGlobalEvaluation[0]->addEvaluation($evaluation);
                                        }
                                        else{
                                            $globalEvaluation = new GlobalEvaluation();
                                            
                                    $globalEvaluation->setCreatedDate(new DateTime());

templates/evaluation/evaluateStudent.html.twig
{% extends 'base.html.twig' %}
	{% block body %}
	<br>
	<div class="container">


		<div class="row">
			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Nom et prénom de l'étudiant :
						{{evaluation.cotation[0].user.firstName}}
						{{evaluation.cotation[0].user.lastName}}
					</label>
				</h3>

				<br>
			</div>

			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Information Stage :<br>
						Référent : {% for referent in evaluation.cotation[0].intership.referents %}
						<li>	{{referent.lastname}} {{referent.firstname}} 
							</li>
						{% endfor %}<br>
						Intervalle de stage : {{evaluation.cotation[0].intership.firstday| date('d/m/Y')}} - {{evaluation.cotation[0].intership.lastday| date('d/m/Y')}}
					</label>
				</h3>
				<h3>
					<label for="exampleFormControlTextarea5">Date de visite :
						{{evaluation.dateCreation | date('d/m/Y')}}
					</label>
				</h3>

				<br>
			</div>

			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Sujet d'évaluation :
						{{evaluation.subject}}
					</label>
				</h3>
				

				<br>
			</div>
			<table class="table table-striped">
				<thead>
					<td>Numéro de la compétence</td>
					<td>Nom de la sous-compétence</td>
					<td>Cotation</td>
				</thead>

				<tbody>
					{% for cotation in evaluation.cotation %}
						{% set index = 0 %}
						<tr>
							{% if index != 0 %}
								<tr>
								{% endif %}
								<td rowspan={{cotation.subskillcotation|length}}>C{{cotation.skill.skillNumber}}
									:
									{{cotation.skill.name}}</td>
								{% for subcotation in cotation.subskillcotation %}
									{% set index = loop.index %}
									<td>{{subcotation.subskill.name}}</td>


									<td>
										{% if subcotation.cotation == 1 %}
											NA--
										{% else %}
											{% if subcotation.cotation == 2 %}
												NA-
											{% else %}
												{% if subcotation.cotation == 3 %}
													A+
												{% else %}
													A++
												{% endif %}
											{% endif %}
										{% endif %}
									</td>
									{% if index != cotation.subskillcotation|length %}
									</tr>
								{% endif %}
							{% endfor %}
						</tr>
						<tr>
							<td colspan="3">Commentaire :
								{% if cotation.comments == "" or cotation.comments == null %}
									Pas de commentaire pour cette compétence.
								{% endif %}
								{{cotation.comments}}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<div class="form-group green-border-focus">
				<label for="exampleFormControlTextarea5">Commentaire Global</label>
				<textarea disabled class="form-control" name="{{evaluation.id}}" rows="3">{{evaluation.comments}}</textarea>
				<br>
			</div>

		</div>
	</div>
{% endblock %}

templates/evaluation/evaluationStudent.html.twig
{% block stylesheets %}
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
{% endblock %}

{% block javascripts %}

	{{ encore_entry_script_tags('app') }}

{% endblock %}
{% block body %}
	<br>
	<div class="container">


		<div class="row">
			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Nom et prénom de l'étudiant :
						{{evaluation.cotation[0].user.firstName}}
						{{evaluation.cotation[0].user.lastName}}
					</label>
				</h3>

				<br>
			</div>

			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Information Stage :<br>
						Référent : {% for referent in evaluation.cotation[0].intership.referents %}
						<li>	{{referent.lastname}} {{referent.firstname}} 
							</li>
						{% endfor %}<br>
						Intervalle de stage : {{evaluation.cotation[0].intership.firstday| date('d/m/Y')}} - {{evaluation.cotation[0].intership.lastday| date('d/m/Y')}}
					</label>
				</h3>
				<h3>
					<label for="exampleFormControlTextarea5">Date de visite :
						{{evaluation.dateCreation | date('d/m/Y')}}
					</label>
				</h3>

				<br>
			</div>

			<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Sujet d'évaluation :
						{{evaluation.subject}}
					</label>
				</h3>
				

				<br>
			</div>
			<table class="table table-striped">
				<thead>
					<td>Numéro de la compétence</td>
					<td>Nom de la sous-compétence</td>
					<td>Cotation</td>
				</thead>

				<tbody>
					{% for cotation in evaluation.cotation %}
						{% set index = 0 %}
						<tr>
							{% if index != 0 %}
								<tr>
								{% endif %}
								<td rowspan={{cotation.subskillcotation|length}}>C{{cotation.skill.skillNumber}}
									:
									{{cotation.skill.name}}</td>
								{% for subcotation in cotation.subskillcotation %}
									{% set index = loop.index %}
									<td>{{subcotation.subskill.name}}</td>


									<td>
										{% if subcotation.cotation == 1 %}
											NA--
										{% else %}
											{% if subcotation.cotation == 2 %}
												NA-
											{% else %}
												{% if subcotation.cotation == 3 %}
													A+
												{% else %}
													A++
												{% endif %}
											{% endif %}
										{% endif %}
									</td>
									{% if index != cotation.subskillcotation|length %}
									</tr>
								{% endif %}
							{% endfor %}
						</tr>
						<tr>
							<td colspan="3">Commentaire :
								{% if cotation.comments == "" or cotation.comments == null %}
									Pas de commentaire pour cette compétence.
								{% endif %}
								{{cotation.comments}}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<div class="form-group green-border-focus">
				<label for="exampleFormControlTextarea5">Commentaire Global</label>
				<textarea class="form-control" name="{{evaluation.id}}" rows="3">{{evaluation.comments}}</textarea>
				<br>
			</div>

		</div>
	</div>
{% endblock %}

templates/evaluation/generatepdf.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<br>
	<div class="container">
	<div class="form-group green-border-focus">
	<div class="form-group green-border-focus">
				<h3>
					<label for="exampleFormControlTextarea5">Nom et prénom de l'étudiant :
						{{evaluation.cotation[0].user.firstName}}
						{{evaluation.cotation[0].user.lastName}}
					</label>
				</h3>

				<br>
			</div>
				<h3>
					<label for="exampleFormControlTextarea5">Information Stage :<br>
					Référent : {% for referent in evaluation.cotation[0].intership.referents %}
					<li>	{{referent.lastname}} {{referent.firstname}} 
							</li>
						{% endfor %}<br>
						Intervalle de stage : {{evaluation.cotation[0].intership.firstday| date('d/m/Y')}} - {{evaluation.cotation[0].intership.lastday| date('d/m/Y')}}
					</label>
				</h3>
				<h3>
					<label for="exampleFormControlTextarea5">Date de visite :
						{{evaluation.dateCreation | date('d/m/Y')}}
					</label>
				</h3>

				<br>
			</div>
		<div class="row">
			Sujet d'évaluation :  <input type='text' disabled placeholder="Sujet d'observation" value="{{evaluation.subject}}"/>
		
			<table class="table table-striped">
				<thead>
					<td>Numéro de la compétence</td>
					<td>Nom de la sous-compétence</td>
					<td>Cotation</td>
				</thead>

				<tbody>
					{% for cotation in evaluation.cotation %}
						{% set index = 0 %}
						<tr>
							{% if index != 0 %}
								<tr>
								{% endif %}
								<td rowspan={{cotation.subskillcotation|length}}>C{{cotation.skill.skillNumber}}
									:
									{{cotation.skill.name}}</td>
								{% for subcotation in cotation.subskillcotation %}
									{% set index = loop.index %}
									<td>{{subcotation.subskill.name}}</td>


									<td>
										{% if subcotation.cotation == 1 %}
											NA--
										{% else %}
											{% if subcotation.cotation == 2 %}
												NA-
											{% else %}
												{% if subcotation.cotation == 3 %}
													A+
												{% else %}
													A++
												{% endif %}
											{% endif %}
										{% endif %}
									</td>
									{% if index != cotation.subskillcotation|length %}
									</tr>
								{% endif %}
							{% endfor %}
						</tr>
						<tr>
							<td colspan="3">Commentaire :
								{% if cotation.comments == "" or cotation.comments == null %}
									Pas de commentaire pour cette compétence.
								{% endif %}
								{{cotation.comments}}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<div class="form-group green-border-focus">
				<label for="exampleFormControlTextarea5">Commentaire Global</label>
				<textarea disabled class="form-control" name="{{evaluation.id}}" rows="3">{{evaluation.comments}}</textarea>
				<br>
			</div>
			{{form_start(form)}}
			{{form_label(form.save,'Générer PDF')}}
			{{form_end(form)}}
			<a class="btn btn-secondary" href="{{path('listEvaluation',{'id':evaluation.cotation[0].user.id,'idIntership':evaluation.cotation[0].intership.id})}}">Revenir à son évaluation</a>
		</div>
	</div>
{% endblock %}

templates/evaluation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste étudiants
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>
	<div class="btn-toolbar mb-2 mb-md-0">
		<h1>Liste des étudiants</div>
	</div>
	<table class="table table-striped">
		<thead>
			<td>Nom de l'étudiant</td>
			<td>Prénom de l'étudiant</td>
			<td>Evaluer</td>
			<td>Clôturer l'évaluation</td>
		</thead>

		<tbody>
			{% for student in students%}
				<tr>
					<td>{{student.lastname}}</td>
					<td>{{student.firstname}}</td>
					<td>
						<a class="btn btn-secondary" href="{{path('listEvaluation',{'id' : student.id,'idIntership':intership.id})}}">
							Evaluer
						</a>
					</td>
					<td>
						<a class="btn btn-success" href="{{path('endEvaluation',{'id':student.id,'idIntership':intership.id})}}">
							Clôturer l'évaluation
						</a>
					</td>
				</tr>
			</tbody>
		{% endfor %}
	</table>
{% endblock %}

templates/evaluation/listEvaluation.html.twig
{% extends 'base.html.twig' %}

templates/evaluation/listFinishedEvaluation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste étudiants
{% endblock %}

{% block body %}
	
	<div class="btn-toolbar mb-2 mb-md-0">
		<h1>Liste des étudiants</div>
	</div>
	<table class="table table-striped">
		<thead>
			<td>Nom de l'étudiant</td>
			<td>Prénom de l'étudiant</td>
			<td>Date de Rencontre</td>
			<td>Consulter l'évaluation</td>
		</thead>

		<tbody>
			{% for evaluation in evaluations%}
				<tr>
					<td>{{evaluation.cotation[0].user.lastname}}</td>
					<td>{{evaluation.cotation[0].user.firstname}}</td>
					<td>{{evaluation.dateCreation| date('d/m/Y')}}</td>
					<td>
						<a class="btn btn-success" href="{{path('viewStudentEvaluation',{'id':evaluation.id})}}">Consulter l'évaluation</a>
					</td>
					
				</tr>
			</tbody>
		{% endfor %}
	</table>
{% endblock %}

templates/evaluation/mailStudent.html.twig
{% block body %}
Bonjour {{evaluation.cotation[0].user.firstName}}
						{{evaluation.cotation[0].user.lastName}}.
Veuillez retrouver ci-dessous un lien pour consulter votre évaluation sur base d'une rencontre effectué le {{evaluation.dateCreation | date('d/m/Y')}}.
	<br>
127.0.0.1:8000/evaluation/consultation/{{evaluation.id}}
<a href="{{path('ConsultationEvaluation',{'id':evaluation.id})}}">Consulter votre évaluation</a>
{% endblock %}

templates/evaluation/viewDocuments.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste étudiants
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>
	<div class="btn-toolbar mb-2 mb-md-0">
		<h1>Liste des étudiants</div>
	</div>
	<table class="table table-striped">
		<thead>
			<td>Nom de l'étudiant</td>
			<td>Prénom de l'étudiant</td>
			<td>Télécharger documents</td>
			
		</thead>

		<tbody>
			{% for student in students%}
				<tr>
					<td>{{student.lastname}}</td>
					<td>{{student.firstname}}</td>
					<td>
						<a class="btn btn-success" href="{{path('downloadFile',{'id':student.id})}}">Télécharger documents</a>
					</td>
					
				</tr>
			</tbody>
		{% endfor %}
	</table>
{% endblock %}