src/Entity/GlobalEvaluation.php
<?php

namespace App\Entity;

use App\Repository\GlobalEvaluationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GlobalEvaluationRepository::class)
 */
class GlobalEvaluation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity=Evaluation::class, mappedBy="globalEvaluation")
     */
    private $evaluations;

    /**
     * @ORM\Column(type="date")
     */
    private $createdDate;

    /**
     * @ORM\OneToMany(targetEntity=GlobalEvaluationSkill::class,mappedBy="globalEvaluation")
     */
    private $skillEvaluation;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $FinalCotation;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $state;

    public function __construct()
    {
        $this->evaluations = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Evaluation[]
     */
    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    public function addEvaluation(Evaluation $evaluation): self
    {
        if (!$this->evaluations->contains($evaluation)) {
            $this->evaluations[] = $evaluation;
            $evaluation->setGlobalEvaluation($this);
        }

        return $this;
    }

    public function removeEvaluation(Evaluation $evaluation): self
    {
        if ($this->evaluations->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getGlobalEvaluation() === $this) {
                $evaluation->setGlobalEvaluation(null);
            }
        }

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->createdDate;
    }

    public function setCreatedDate(\DateTimeInterface $createdDate): self
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    /**
     * @return Collection|GlobalEvaluationSkill[]
     */
    public function getGlobalEvaluationSkill(): Collection
    {
        return $this->skillEvaluation;
    }

    public function addGlobalEvaluationSkill(GlobalEvaluationSkill $evaluation): self
    {
        if (!$this->skillEvaluation->contains($evaluation)) {
            $this->skillEvaluation[] = $evaluation;
            $evaluation->setGlobalEvaluation($this);
        }

        return $this;
    }

    public function removeGlobalEvaluationSkill(GlobalEvaluationSkill $evaluation): self
    {
        if ($this->skillEvaluation->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getGlobalEvaluation() === $this) {
                $evaluation->setGlobalEvaluation(null);
            }
        }

        return $this;
    }

    public function getFinalCotation(): ?int
    {
        return $this->FinalCotation;
    }

    public function setFinalCotation(?int $FinalCotation): self
    {
        $this->FinalCotation = $FinalCotation;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

}

templates/evaluation_student/consultation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consultation
{% endblock %}

{% block body %}
	
	<div class="btn-toolbar mb-2 mb-md-0">
		<h1>Consultation</div>
	</div>
    
			{% for evaluationGlobal in evaluations%}
            <h2>Année académique : {{evaluationGlobal.evaluations[0].cotation[0].intership.ansco}}</h2>
            {% if evaluationGlobal.state == "Fini" %}
            <a class="btn btn-success" href="{{path('consultationResult',{'id':evaluationGlobal.id})}}">Consulter l'évaluation de stage</a>
{% endif %}	<table class="table table-striped">
		<thead>
			<td>Nom de l'évaluateur</td>
			<td>Prénom de l'évaluateur</td>
			<td>Date de Rencontre</td>
			<td>Consulter l'évaluation</td>
		</thead>

		<tbody>
            {% for evaluation in evaluationGlobal.evaluations %}
                
				<tr>
					<td>{{evaluation.user.lastname}}</td>
					<td>{{evaluation.user.firstname}}</td>
					<td>{{evaluation.dateCreation| date('d/m/Y')}}</td>
					<td>
						<a class="btn btn-success" href="{{path('ConsultationEvaluation',{'id':evaluation.id})}}">Consulter l'évaluation</a>
					</td>
					
				</tr>
			</tbody>
            {% endfor %}
	</table>
    
		{% endfor %}
{% endblock %}

templates/evaluation_student/evaluation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auto-Évaluation
{% endblock %}
{% block body %}
	<div class="container">
		<div class="row">
			<h1>
				<u>
					Auto-Évaluation
				</u>
			</h1>
<input type='text' id="textSubject" name="{{evaluation.id}}" placeholder="Sujet d'observation" value="{{evaluation.subject}}"/>
Date de la visite :
<input type='date' id="date" name="{{evaluation.id}}" value="{{evaluation.dateCreation | date('Y-m-d')}}"/>			

			{% for cotation in evaluation.cotation%}
				{% set indexSkill = loop.index0 %}

				<h2>
					Compétence :
					{{cotation.skill.name}}
				</h2>


				<table class="table table-striped">
					<thead>
						<td>Numéro de la compétence / sous-compétence</td>
						<td>Nom de la compétence / sous-compétence</td>
						<td>Cotation</td>
					</thead>

					<tbody>
						{% for subcotation in cotation.subskillcotation %}
							<tr>

								<td>{{cotation.skill.skillNumber}}.{{subcotation.subskill.number}}</td>
								<td>
									{{subcotation.subskill.name}}</td>

								<td>
									<select class="form-select form-select-lg mb-3" id="{{subcotation.id}}" aria-label="form-select-lg example">

										<option {% if subcotation.cotation == 0 %} selected="selected" {% endif %} disabled value="0">Évaluer la compétence</option>
										<option {% if subcotation.cotation == 1 %} selected="selected" {% endif %} value="1">NA--</option>
										<option {% if subcotation.cotation == 2 %} selected="selected" {% endif %} value="2">NA-</option>
										<option {% if subcotation.cotation == 3 %} selected="selected" {% endif %} value="3">A+</option>
										<option {% if subcotation.cotation == 4 %} selected="selected" {% endif %} value="4">A++</option>
									</select>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<br>
				<div class="form-group green-border-focus">
					<label for="exampleFormControlTextarea5">Commentaire sur la compétence :
						{{cotation.skill.name}}</label>
					<textarea class="form-control" name="skillComments"id="{{cotation.id}}" rows="3">{{cotation.comments}}</textarea>
					<br>
				</div>
				<hr style="height:4px;border-width:0;color:blue;background-color:red">
				<br>

			{% endfor %}
						<div class="form-group green-border-focus">
				<label for="exampleFormControlTextarea5">Commentaire Global</label>
				<textarea class="form-control" id="{{evaluation.id}}" name="globalComments"rows="3">{{evaluation.comments}}</textarea>
				<br>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	{{parent()}}<script>

		$(document).ready(function () { // When you change your cotation
$("select").each(function () {
$(this).change(function () {
var subcotation = $(this).attr('id')
var cotation = $(this).children("option:selected").val()
$.ajax({
url: "/evaluation",
type: 'get',
data: {
'subSkillCotation': subcotation,
'cotation': cotation
},
cache: false,
datatype: 'json',
success: function (data, status) {},
error: function () {}
});

})
})

// When you change your comments.

$("textarea").each(function () {
$(this).change(function () {
	var cotation = $(this).attr('id')
var comments = $(this).val()
if($(this).attr('name')=="skillComments"){

$.ajax({
url: "/evaluationComments",
type: 'get',
data: {
'comments': comments,
'cotation': cotation
},
cache: false,
datatype: 'json',
success: function (data, status) {},
error: function () {}
});
}
else{
console.log(comments)
$.ajax({
url: "/evaluationArchiveComments",
type: 'get',
data: {
'comments': comments,
'evaluation': cotation
},
cache: false,
datatype: 'json',
success: function (data, status) {},
error: function () {}
});
}
})
})

// when you change the subject
$("#textSubject").change(function () {
var evaluation = $(this).attr('name')
var value = $(this).val()
$.ajax({
url: "/evaluationArchiveSubject",
type: 'get',
data: {
'subject': value,
'evaluation': evaluation
},
cache: false,
datatype: 'json',
success: function (data, status) {},
error: function () {}
});
})
$("#date").change(function () {
var evaluation = $(this).attr('name')
var value = $(this).val()
	$.ajax({
url: "/evaluationArchiveDate",
type: 'get',
data: {
'date': value,
'evaluation': evaluation
},
cache: false,
datatype: 'json',
success: function (data, status) {},
error: function () {}
});
})
})
	</script>
{% endblock %}

templates/evaluation_student/listIntership.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des stages
{% endblock %}

{% block body %}
	


	<div class="btn-toolbar mb-2 mb-md-0">
		<h1>Liste de stages</h1>
		<table class="table table-striped">
			<thead>
				<td>Lieu</td>
				<td>Section / sous-section</td>
				<td>Bloc</td>
				<td>Début de stage - Fin de stage</td>
				<td>Année académique</td>
				<td>Envoyer un/plusieurs document(s)</td>
				<td>S'auto-évaluer</td>
			</thead>
			<tbody>

				{% for intership in interships %}
					<tr>
						{% if intership.applicationField.parent.type != "sub_section" %}

							<td>{{intership.applicationField.parent.parent.name}}</td>
							<td>
								{{intership.applicationField.parent.name}}</td>
						{% else %}
							<td>{{intership.applicationField.parent.parent.parent.parent.parent.name}}</td>
							<td>{{intership.applicationField.parent.parent.parent.parent.name}}</td>

							<td>{{intership.applicationField.parent.parent.parent.name}}</td>
							<td>{{intership.applicationField.parent.parent.name}}
								/
								{{intership.applicationField.parent.name}}</td>

						{% endif %}
						<td>{{intership.applicationField.name}}</td>
						<td>{{intership.firstDay | date("d/m/Y")}}
							-
							{{intership.lastDay | date("d/m/Y") }}</td>
						<td>{{intership.ansco}}</td>
						<td>
							<a class="btn btn-success" href="{{path('sendDocument',{'id':intership.id})}}">Partager des documents</a>
						</td>
						<td>
						<a class="btn btn-success" href="{{path('autoEvaluation',{'id':intership.id})}}">S'auto-évaluer</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
	</table>
</div>{% endblock %}

templates/evaluation_student/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Évaluation de
	{{evaluation.evaluations[0].cotation[0].user.lastname}}
	{{evaluation.evaluations[0].cotation[0].user.firstname}}
{% endblock %}
{% block body %}
	<div class="container">
		<div class="row">
			<h1>
				<u>
					Évaluation de
					{{evaluation.evaluations[0].cotation[0].user.lastname}}
					{{evaluation.evaluations[0].cotation[0].user.firstname}}
				</u>
			</h1>

<h2>Année académique :
{{evaluation.evaluations[0].cotation[0].intership.ansco}}</h2><br>
				

    
                


				<table class="table table-striped">
					<thead>
						<td>Numéro de la compétence</td>
						<td>Nom de la compétence</td>
						
                        <td>Note finale de la compétence</td>
					</thead>

					<tbody>
                        {% for globalSkill in evaluation.globalEvaluationSkill %}
				        	<tr>

								<td>C{{globalSkill.skill.skillNumber}}</td>
								<td>{{globalSkill.skill.name}}</td>


								<td>
                               
										{% if globalSkill.cotation == 1 %}
											<font style='color:red'>Non acquis</font>
										{% else %}
											{% if globalSkill.cotation == 2 %}
												En phase d'acquisition
											{% else %}
													Acquis
											{% endif %}
										{% endif %}
									</td>

							</tr>
           
{% endfor %}
					</tbody>
				</table>

                <h3>Cote finale /20 : {{evaluation.finalCotation}}</h3>
               
			</div>
            
				<br>
			

					
			</div>
		</div>
	</div>
{% endblock %}

templates/evaluation_student/sendDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}Envoi documents
{% endblock %}

{% block body %}
	


	<div class="btn-toolbar mb-2 mb-md-0">
   
        {{form_start(form)}}
        {{form_row(form.file)}}
			<button type="submit" id="btnSubmit" class="btn btn-success">
				Envoyer le fichier pdf</button>
        {{form_end(form)}}
</div>{% endblock %}